# uv configuration for Meeting Notes Handler

[tool.uv]
# Always use Python 3.12
python = "3.12"

# Development mode settings
dev-dependencies = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "pytest-mock>=3.10",
    "black>=23.0",
    "isort>=5.12",
    "flake8>=6.0",
    "mypy>=1.0",
    "build>=1.0",
]

# Environment settings
[tool.uv.pip]
index-url = "https://pypi.org/simple"